### ISSUE TITLE
Probably a non-issue but...

### ISSUE THREAD

**Issue by xornand** [matthewbauer/bauer#2]
I ran your script on a fresh *nix (as in the general POSIX *nix) install. I suffered a hard drive crash and lost >10 years of conf files :cry: but your starter looked great so I decided to go bang with it. I copy paste easy install after four seconds of scanning to make sure your script wont rm -rf /var or whatever, and off I go. I then proceeded to follow your instructions and I get a bunch of blah blah file not found. I scroll up and see something on line 22 didn't run, so I pull your file and check it out. Whoooooooooops, git dependency! Easy enough fix, mind you.

My issue was clearly a one off , since uh, this is github, so I think it's a completely implied pre-req that you...have git... but with all those stupid docker mini-services bullshit out there, odds are someone even dumber than me might run into a similar issue, struggle with the script on a fresh install for a few hours, and proceed to take the old little-league baseball bat sitting in the corner to his monitor

**Comment by matthewbauer** [comment]
Yeah good point, NixOS at least doesn't have Git installed by default! I suppose we can install it with nix-env if it's not there.
