### ISSUE TITLE
Whydoes :ensure packageName work but :ensure t does not?

### ISSUE THREAD

**Issue by codygman** [matthewbauer/bauer#5]
I first [tried adding my helm config in this commit](https://git.sr.ht/~codygman/codygman-emacs/commit/62a3f615117b84ad9f8b6da550e01629572df3bb).

That didn't work so I [simplified the helm use-package stanza in this commit](https://git.sr.ht/~codygman/codygman-emacs/commit/7962e534c0a4ca3dafc7f7cdb3e04ba0f995973a).

At [this commit](https://git.sr.ht/~codygman/codygman-emacs/commit/7962e534c0a4ca3dafc7f7cdb3e04ba0f995973a) I set ensure equal to `helm` because I noticed in [the solarized example you provided in my earlier pull request](https://github.com/matthewbauer/bauer/pull/3#issuecomment-498895379) your ensure was set to `solarized`.

I'm not sure why this made helm work, since other use-package stanzas in your config seem to use `:ensure t`.

Since I'm trying to move my main config to a fork of bauer, I want to understand these things so I can maintain it in the future :)

**Comment by matthewbauer** [comment]
I set ```use-package-always-ensure``` to ```t``` so by default it should download the package. The reason ```:ensure packageName``` is sometimes needed is that the "package name" differs from the Lisp "feature name". For instance with spacmacs-theme the MELPA package name is "spacemacs-theme" while the entry point (what is require'd) is "spacemacs-common".
